name = "Yarn.Modpack.Prism"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d21ab1be206dbf5368b8b50502bf32f9244b3bd4655730bde98e60f806b05f9"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
