name = "Yarn.Modpack.Prism"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b560b171f3e0585dd69c0c3d2c8311408fdf350b648d7c08ef612ed87a4bdad0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
