name = "Yarn.Modpack.Prism"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab637664728fed1fb90f2e4ed019b0af46ec65d5ddd69932634bb48a7e9d2d76"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
